# Generated by Django 5.0.3 on 2024-03-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
