# Generated by Django 5.0.3 on 2024-03-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_car_image_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
